name: flask ci-pipeline

on:
    push:
        branches:
            - main

jobs:
    flask-app-1:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: Installing modules and dependencies
              run: |
                python -m pip install  --upgrade pip
                pip install -r requirements.txt

            - name: Test cases
              run: echo "All the tests passed! Hurray, my python files got downloaded, packages got updated automatically, everytime I do a push on my main branch!!!"
